### ISSUE TITLE
Initial exercise order

### ISSUE THREAD

**Issue by tgecho** [exercism/xelm#34]
Now that we have a decent starting set of exercises (pending PR merges), I'm wondering about a good starting order. I've generally thrown them in haphazardly, somewhat based on the order in the other tracks I've pulled them from.

The current order, as of https://github.com/exercism/xelm/pull/31 is this:

1. hello-world
1. leap
1. pangram
1. rna-transcription
1. hamming
1. word-count
1. bob
1. run-length-encoding
1. difference-of-squares
1. anagram
1. raindrops
1. triangle

My questions for @kytrinyx, @parkerl and whoever else:

1. Is there a canonical/recommended order of exercises?
1. Is it a correct assumption that once launched it would be a bad idea to add new exercises anywhere other than the end?
1. Assuming 2 is correct, might it be worthwhile to sort the first batch of exercises by some subjective measure of difficulty to provide a nice onramp?

**Comment by kytrinyx** [comment]
1. No, there's no canonical/recommended order.
2. Nope, you can add them anywhere. People who have progressed beyond the point that you add it will get it the next time they fetch (fetch order is "earliest exercise that they have not yet done").
3. I don't think it's anything to worry about. I generally try for _roughly in order of difficulty_, but often I discover as people start doing the exercises that (a) I was wrong, and (b) some exercises are particularly interesting to start with because of language stuff, and (c) sometimes exercises are particularly boring in a language (and can either be moved earlier or removed altogether).

**Comment by parkerl** [comment]
Based on the answers above are we good with the current order? Looks ok to me.

**Comment by tgecho** [comment]
I feel pretty good about the "don't overthink it" message. Thanks for that!

I think tonight I'll still take a glance through and try to at least make sure the first few exercises are the less intimidating of the bunch.

**Comment by kytrinyx** [comment]
I think this is solved. Closing :)
