### ISSUE TITLE
Wrong test in Triangle exercise

### ISSUE THREAD

**Issue by jgrenat** [exercism/xelm#98]
Hi,

I think I've noticed a mistake inside the Triangle test suit:

```elm
test "triangles violating triangle inequality are illegal 2"
     (assertEqual (Err "Violates inequality") (triangleKind 2 4 2))
```

This one is a flat triangle and doesn't violate the inequality.

**Comment by kytrinyx** [comment]
Yeah, it's a degenerate triangle, but doesn't violate the triangle inequality. We've had a huge discussion about this not too long ago:

https://github.com/exercism/x-common/issues/202

I think maybe this test suite got added sometime in the middle of that confusion, and didn't get fixed with the others.

Would you be willing to submit a patch that fixes it?

**Comment by Emiluren** [comment]
Sorry for just jumping in here but I felt like doing this so I am working on it. I hope that is ok.
